scrape_configs:
  - job_name: 'graylog'
    scrape_interval: 15s
    metrics_path: '/api/plugins/org.graylog.plugins.metrics.prometheus/metrics'
    basic_auth:
      username: admin
      password: admin
    static_configs:
      - targets: ['graylog:9000']
